### PR TITLE
Autoprefixer support for SASS compiler

### PR DESCRIPTION
**Pull request by Krusen**
I really wanted (=needed) autoprefixer support for the SASS compiler and wanted to avoid switching to npm/gulp if possible - so I decided to try and implement it in this extension myself.

I had to update Node as [postcss-cli](https://github.com/postcss/postcss-cli) requires Node >= 4. I went with latest Node 6.x (LTS). `binding.node` has been rebuild and updated as well.

Basically all it does is to include npm modules `postcss-cli` and `autoprefixer` and then pipe the output from `node-sass` to `postcss` and use that as the final output.

Other issues that has been fixed along the way:
- The current build error for the babel compiler test. Caused by a slightly different format of `sourceMappingUrl` which includes `chartset=UTF-8;`
- Wrong paths in SCSS source maps caused by `--source-map=false`

### CODE REVIEW

**Comment by madskristensen** [comment]
Node 6 is not guaranteed in VS. It ships with version 5.2 and so the user have to manually install Node 6+ for this to work

**Comment by Krusen** [comment]
But doesn't it use the `node.exe` from the temp folder?

**Comment by madskristensen** [comment]
Doh! You are right. It totally does

**Comment by madskristensen** [comment]
Thanks for the PR!!

**Comment by Krusen** [comment]
Cool, happy to help!

**Comment by IanMuirhead** [comment]
@Krusen @madskristensen 

I'm struggling to get this to work on our project.  Hoping you could provide some feedback as to what I'm missing here.

We're running the latest stable version -- 1.11.375, which I believe includes this change.

```
[
  {
    "outputFile": "Common/Resources/master.css",
    "inputFile": "Common/Resources/master.scss",
    "options": {
      "sourceMap": false, 
      "autoPrefix": "last 2 versions, > 5%"
    }
  }
]
```

The sourceMap option is working -- but no dice on the autoPrefix.

Any ideas?

**Comment by Krusen** [comment]
@IanMuirhead Are you sure you are using 1.11.375? The stable version is still 1.11.326 and haven't been updated since march.

**Comment by IanMuirhead** [comment]
@Krusen yep - pretty confident! 

image

**Comment by Krusen** [comment]
Ah, that's the package for build servers, right? Is your issue when building your solution or when using the extension to compile sass in Visual Studio (e.g. on save or right click > compile)?

**Comment by IanMuirhead** [comment]
@Krusen 

It's the package we're installing locally for development as well. 

The issue I'm having is compiling Sass in VS.

**Comment by IanMuirhead** [comment]
@Krusen Got it working as expected out of the box.  Was having some issues with caching or stale packages in my environments.

thanks for your time!

**Comment by yairza** [comment]
@IanMuirhead Any luck here? having the same issue

**Pull request merged**
