### PR TITLE
Added partials support + compiling dependent files when saving an scss file

### PR DESCRIPTION
**Pull request by PaulVrugt**
this should fix both issue #169  and issue #171 

Like I said in my original pull request: I'm new to the code and also to github. This seems to fix the issues, but I might be doing something very wrong or thinking to simplistic. If so, please let me know so I can correct it.

So let me know what you think :)

### CODE REVIEW

**Comment by madskristensen** [comment]
First of all, thanks for the pull request. It is very rare any of my extensions have any other contributors, so that's for that.

A few questions:

**Partials support**
What is the purpose of this? If you don't want a file compiled, don't add it to `compilerconfig.json`. I don't understand this.

**Dependant files**
I don't understand this one either. If a Sass file (foo.scss) contains `@import` directives, then those imported files will automatically be included in the compiled output when foo.scss is being saved. They don't need to be compiled separately.

The case when you change a referenced file (variables.scss) that is imported by foo.scss, it should already trigger recompilation of foo.scss unless variables.scss has been added to `compilerconfig.json` to be compiled separately.

**Comment by PaulVrugt** [comment]
Thank you for the quick reply!

Your answer sheds light some light on the issues were are currently having with the plugin, and judging from the q&a section of the plugin a lot of other people have too.

Not adding the files marked with an underscore to the compilerconfig.json file makes sense. Regardless of that, files starting with an underscore are from the definition of sass partial files. Our expectation was that the web compiler addin (as its predecessor in studio 2013) would automatically pick up on this and not compile it.

The dependent file behavior you describe is related to this. I'll test it on Monday when I'm back at the office but the part about automatically recompiling dependent files when the file itself is a partial (which you should apparently define it by not adding it to the compilerconfig.json) would solve a second problem we are having.

I think the underlying issue is actually the entire need for the compilerconfig.json. We want to migrate from studio 2013 to 2015, and have a very large project containing thousands of scss files. We are not enthusiastic about having to maintain a compilerconfig.json file with thousands of files in them. In studio 2013 there was no need for a compilerconfig.json and all compilation was done automatically and partials were recognized by the underscore. Maybe the feature I am looking for is a feature in which adding or renaming an scss file in visual studio 2015 will automatically add the file to the compilerconfig.json. This behavior could be a setting for the extension.

Like I said, I will check if the behavior you describe will solve the 2 largest issue we are currently having. If that is the case, the changes I made to the code will not be necessary. However, the feature I am suggesting might be interesting to a lot of people. If I look at the Q&A a lot of people a struggling with similar issues.

I'd like to know your thought and would of course like to contribute to any code changes that might be needed for the feature I am suggesting or an alternative you might think of.

**Comment by PaulVrugt** [comment]
Goodmorning Mads,

I've discussed your reaction with a fellow developer working on our scss'es. About the dependent files, we still have an issue with the current implementation:

You state:
*The case when you change a referenced file (variables.scss) that is imported by foo.scss, it should already trigger recompilation of foo.scss unless variables.scss has been added to  compilerconfig.json  to be compiled separately.*

We actually have files that have to be compiled separately, and are also included in other scss files. In this case the dependency will not be automatically resolved, but I do think this is a valid situation for sass.

**Comment by madskristensen** [comment]
The problem is with performance. if you want all .scss files to be recompiled when any .scss file changes, then that could take a long time. That's the reason I designed it this way. It may be a valid scenario for Sass, but I think that most people will be severely negatively impacted by this change.

**Comment by PaulVrugt** [comment]
I think we have a misunderstanding here. I'm not suggesting to recompile all scss files when any of them change. What I'm proposing is to make the extension smart enough so that it knows what scss files to recompile when a file changes, by checking the import statements in the scss file. The code in my pull request does this right now by simply reading the scss files, but we could create a map that is updated per file when a file changes, so we only need to lookup which files have changed after a save to recompile the correct files.

This change will actually improve performance compared to the current implementation. The current implementation will recomplile ALL scss files when a scss file is saved that is not present in the compilerconfig, which is even more of an performance issue. We have thousands of scss files in our project. When saving a scss partial we don't want ALL of them to be recompiled, but only the ones that are actually dependent on the partial.

I'll try to find time to create a new pull request this week to show my suggestion. Judging from the current implementation and your reaction I believe it will be an improvement to the current implementation.

**Comment by madskristensen** [comment]
AFAICT, the PR figures out what files are being imported by the current file, but the issue is the reverse of that. Namely, being able to identify what files reference the file being modified. It's the exact opposite scenario and that is one that cannot be resolved unless all .scss files in the project are parsed to create the import tree.

**Comment by PaulVrugt** [comment]
Hello,

I've been working on a change that will support dependencies without a performance impact, that will even improve dependency compilation compared to the current implementation. I have it working, but it still needs some cleaning before i can make a pull request. The change resolved dependencies once (which takes a few tenth of a second during the first scss compile in our project with over 500 scss files), and will use and update these dependencies when compiling and changing files. I think this will be a significant improvement over the current behavior.

As soon as I have it ready i will create a pull request. I'm looking forward to you opinion on it.

**Comment by madskristensen** [comment]
Nice! Should this PR be closed then?

**Comment by PaulVrugt** [comment]
Apparently not, since my commits have been added to this pull request. I've reimplemented the dependency behavior. I've created a generic DependencyService that can process dependencies of all supported file types. I've only implemented dependencies for scss/sass files, but this can be extended to support other file types.

I've tested the new behavior on our own project and it seems to do the trick. Recompiling a partial now only triggers the recompile of all files that actually are dependent on the partial, and not ALL 500 scss files on our project. The extension now also supports non-partials that are referenced in other scss files.

Please let me know what you think

**Comment by madskristensen** [comment]
Looks great. Thanks again!!

I left a few comments in the code

**Comment by PaulVrugt** [comment]
I've updated the code and processed the two remarks you left. I have no experience with LESS, but I've created a little test project and this seems to do the trick. The syntax seems to be quite similar.

**Pull request merged**
