### PR TITLE
Compatibility with .NET CLI version of MsBuild

### PR DESCRIPTION
**Pull request by djanosik**
I've made some changes to make WebCompiler task compatible with .NET CLI version of MsBuild:

- WebCompiler project now targets `net46`, `netstandard2.0` and `netcoreapp2.0`.
- The **BuildWebCompiler.targets** now supports .NET Core MsBuild. 
- I have also removed the `BuildDependsOn` attribute, because I think it's better to use the `BeforeTargets` attribute. The `WebCompile` target will now always run before `BundleMinify` and `BeforeCompile` targets. But it will run only once of course.
- **AjaxMin** has been replaced with **NUglify**. It required minimum changes.
- The **BuildWebCompiler.nuspec** file has been removed.

It should fix issues https://github.com/madskristensen/WebCompiler/issues/328, https://github.com/madskristensen/WebCompiler/issues/237 and https://github.com/madskristensen/WebCompiler/issues/321.

### CODE REVIEW

**Comment by djanosik** [comment]
@madskristensen I am not sure whether I should update the build script. I have no idea how do you handle versioning, etc.

**Comment by djanosik** [comment]
Ok, I think I've managed to fix the build configuration.

**Comment by 304NotModified** [comment]
@madskristensen can this be merged?

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
